name: 'Run infradsl'
author: 'nigel.magnay@nirima.com'
description: 'Do some Infra stuff'
branding:
  icon: 'info'
  color: 'green'
inputs:
  file:
    description: filename
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/magnayn-mns/infradsl:main'
  args:
    - ${{ inputs.file }}
