name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build-container:
    runs-on: ubuntu-latest
    name: Building container
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Gradle build
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - run: |
          ./gradlew script-definition:jib  -Djib.to.image=${{ steps.prep.outputs.tags }} -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.SAML_GITHUB_TOKEN }}
